name: Lint and Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run lint.sh
        working-directory: backend
        run: bash scripts/lint.sh