name: Lint Backend Code

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # specify your Python version

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install flake8

      - name: Run flake8
        run: flake8 backend
