name: Lint and Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install flake8 mypy isort

      - name: Run flake8
        working-directory: backend
        run: flake8 . --config=setup.cfg

      - name: Run mypy
        working-directory: backend
        run: mypy --config-file=setup.cfg .

      - name: Run isort
        working-directory: backend
        run: isort --check --diff --config=setup.cfg .
